# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DQQxBwGrCJMbeYrsNs4d7xKakG+T6BXKhWSeMrnx1PW/vPDYITU9B4ulErhsQZiTX/bJlM/3UI+vKNIQbkh+i5AbSc8570gXWQD0/Ne3mkjXk8BXAMxOLEmEtmrX/FgSvKPstHE4u3hBB25lUcWOGhwmYNXUWLOWz7nx2g6NB5Tos77YeyMhlEUVxll7piWgul1Af1/uiv7BLJpMVQJm7oOPJTmtbwZwZ/r5G8/nK0DUgjhVpruyNHCpbfwiHx6lC3+a9qlqYxOVaH974DQDyTdLBIXRojfSR15SFzx13EUK7RlqCFRYx/kIX4bC28BcaXISneJ9l19kJwfa4a+8RQMgHxiuMT27XAJ+T8OP4YxH8sD+pw4YyyglXvfz+5WwXEx1gt2EfqDa4sE+FC7zEf0YRbwJDKHdD2A9ugY98L+NCXtIwWyEt8vCNl6NQwbZsotuUp12bqVr+SBCMwNHAOzHDOgiQOceD9YXD06zK8SYVPIRUuYlG8Dy/AEyj95TBpTfTU/vd0/o4XybODq1OKEKqg2uV4R69NrmQXx+rPSXpuTioxunuWLHmaDbisJh+0usMy4dGOVzBC5U9GYnJeQh5KnM6rBADSvqmezeyqqdmRxINNkC6b22ySephEdBWtaLieRRZYhWfcc55oLH43XgmpBH4aEWXziRTSaXy/U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
