travis:
  secure:
    BINSTAR_TOKEN: DQQxBwGrCJMbeYrsNs4d7xKakG+T6BXKhWSeMrnx1PW/vPDYITU9B4ulErhsQZiTX/bJlM/3UI+vKNIQbkh+i5AbSc8570gXWQD0/Ne3mkjXk8BXAMxOLEmEtmrX/FgSvKPstHE4u3hBB25lUcWOGhwmYNXUWLOWz7nx2g6NB5Tos77YeyMhlEUVxll7piWgul1Af1/uiv7BLJpMVQJm7oOPJTmtbwZwZ/r5G8/nK0DUgjhVpruyNHCpbfwiHx6lC3+a9qlqYxOVaH974DQDyTdLBIXRojfSR15SFzx13EUK7RlqCFRYx/kIX4bC28BcaXISneJ9l19kJwfa4a+8RQMgHxiuMT27XAJ+T8OP4YxH8sD+pw4YyyglXvfz+5WwXEx1gt2EfqDa4sE+FC7zEf0YRbwJDKHdD2A9ugY98L+NCXtIwWyEt8vCNl6NQwbZsotuUp12bqVr+SBCMwNHAOzHDOgiQOceD9YXD06zK8SYVPIRUuYlG8Dy/AEyj95TBpTfTU/vd0/o4XybODq1OKEKqg2uV4R69NrmQXx+rPSXpuTioxunuWLHmaDbisJh+0usMy4dGOVzBC5U9GYnJeQh5KnM6rBADSvqmezeyqqdmRxINNkC6b22ySephEdBWtaLieRRZYhWfcc55oLH43XgmpBH4aEWXziRTSaXy/U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
